# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/constraints/zybo_z7_20.xdc

# XDC: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/constraints/cva6_fpga.xdc

# IP: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_master || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_master} -quiet] -quiet

# IP: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_slave || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_slave} -quiet] -quiet

# IP: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_blk_mem_gen || ORIG_REF_NAME==xlnx_blk_mem_gen} -quiet] -quiet

# IP: /home/diskouna/Bureau/INSA/INSAi_CVA6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_clk_gen || ORIG_REF_NAME==xlnx_clk_gen} -quiet] -quiet
